### ISSUE TITLE
[LFP] TODO List

### ISSUE THREAD

**Issue by SkyLeite** [RodrigoLeiteF/WeebBot-v2#13]
**\- Bugs and unintended stuff**
- [ ] Make #matchmaking commands only
- [x] Fix !changePID ""
- [x] Fix no nickname (when user's discord username is the same as their nickname)
- [ ] Fix !changePID "@everyone"
- [x] Fix !join logic (loop through entries looking for a match)
- [x] finishQuest still doesn't work 100% of the time

**\- Requested features**
- [ ] Ping when a group is almost full
- [ ] Ping @everyone in group when someone joins
- [ ] Better group board

**\- System improvements**
- [x] Lock shit (Thanks @Zogzer)
- [x] Make !changePID also change owner / member name

**Comment by KazeSenoue** [comment]
Moved to @pso2-matchmaking

**Comment by SkyLeite** [comment]
Moved to https://github.com/KazeSenoue/pso2-matchmaking/
