### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by SkyLeite** [RodrigoLeiteF/WeebBot-v2#14]
- [x] Include EQs that happen on every ship
- [x] Bumped alerts
- [ ] Daily order alerts
- [ ] Gatherer link in `mtg`

## Shadowverse
- [ ] [this garbage](http://i.imgur.com/bfo0Tl2.png)
- [x] [List craft  (faction)](https://i.imgur.com/PZzF4VK.png)
- [ ] Fix multiple matches for alternate art cards (add column with ID for the alt art card)
- [x] Remove attack / defense and evolved art from amulets
- [ ] Clean up text on card descriptions in the database. HTML tags should be ignored.

## MTG

- [ ] Add loyalty for Planeswalker cards

**Comment by SkyLeite** [comment]
No use for this anymore
